Fancy-Weather
AlexGrin1/Fancy-Weather pull request #1
Opened 2021-05-24 15:24 UTC by AlexGrin1

2021-05-28 10:46 UTC, zenby reviewed
- сабмит на форме с городом не работает (должно работать на ввод enter)
- карта не перемещается на введенный город
- ломается приложение при нажатии несколько раз на кнопку search с городом

2021-05-28 10:46 UTC, zenby commented on src/js/getTime.js
> +}
тут не должно быть таких сеттаймаутов через рекурсию. Время обновления можно сделать через setInterval

2021-05-28 10:46 UTC, zenby commented on src/js/getTime.js
> +}
эту функцию можно переделать с помощью [padStart](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/padStart)

2021-05-28 10:46 UTC, zenby commented on src/js/weather.js
> +    const i = await console.log(data);
что эта строка делает и для чего она здесь?

2021-05-28 10:46 UTC, zenby commented on src/js/weather.js
> +}
если ввести город и несколько раз кликнуть по нему, то сломаются дни с погодой. Также по возможности на  ты можешь использовать innerhtml тогда у тебя меньше тут кода будет и он будет понятнее выглядеть. Так же эта функция сейчас очень большая, либо вынеси в отдельные более мелкие, и / или переделай через innerHtml

2021-05-28 10:46 UTC, zenby commented on src/styles/_constants.scss
> +}
Ты поместил кучу стилей в файл _constants? Почему? Он ведь не для этого нужен.

2021-05-29 09:48 UTC, zenby commented on package.json
> +    "start": "webpack-dev-server --mode development --open"
у тебя команды start & test работают если не нужны, то удали их

2021-05-29 09:48 UTC, zenby commented on src/js/getTime.js
> +setInterval(showTime, 1000);
зачем 2 setInterval когда все действия (showTime & getDate) можно сделать в одном? 
getDate плохое название для этой функции

2021-05-29 09:48 UTC, zenby commented on src/js/weather.js
> +}
```
const on3days = document.querySelectorAll(".weatherOn3Days");
on3days.innerHTML = '' 
```
и цикл не нужен

2021-05-29 09:48 UTC, zenby commented on src/js/weather.js
> +}
зачем ты используешь debounce в своем приложении, объясни плз?

2021-05-29 09:48 UTC, zenby commented on src/js/weather.js
> +});
плохо написано 
- добавляешь 2 обработчика с похожим кодом
- с элементом form в виде враппера, ты сможешь сделать один обработчик на submit
- чтобы не писать `inputCity.value !== ""` здесь было бы уместно использовать нативную html валидацию с тем, что инпут не может быть пустым

2021-05-29 09:48 UTC, zenby commented on src/js/weather.js
> +function create(data) {
плохое название функции

2021-05-29 09:48 UTC, zenby commented on src/js/weather.js
> +}
эта функция слишком громоздкая. Разбиение ее на более мелкие + использование innerHtml может помочь сделать ее более наглядной и понятной.

2021-05-29 09:48 UTC, zenby commented on src/js/weather.js
> +  });
возможно стоит сделать так, чтобы карта не двигалась пользователем?

2021-05-29 09:48 UTC, zenby commented on src/js/weather.js
> +  }
в catch стоит обработать ошибку, если она говорит о том, что погода для введенного города не найдена. Например когда пользователь ввел город на русском языке.

2021-05-29 20:03 UTC, AlexGrin1 commented on src/js/weather.js
> +}
это не работает.  вместо того,что бы удалить элементы, потом просто добавляются новые. Одним этим решением не обойтись

2021-05-29 20:04 UTC, AlexGrin1 commented on src/js/weather.js
> +}
при частом нажатии на search, начинает ломаться(не успевает удалять элементы). Использую debaunce для того, что бы ограничить частоту вызова

2021-05-29 20:07 UTC, AlexGrin1 commented on src/js/weather.js
> +  });
хм, а зачем? по-моему прикольно

2021-05-31 12:00 UTC, zenby commented on src/js/weather.js
> +}
значит ты что-то делаешь неверно, обычным innerHtml можно сделать, чтобы это работало

2021-05-31 12:05 UTC, zenby requested changes

2021-05-31 12:05 UTC, zenby commented on src/js/weather.js
> +  }
вопрос остался открытым, то, на что ты заменил не должно работать / или работает неверно.

2021-05-31 12:05 UTC, zenby commented on src/js/weather.js
> +}
ты решаешь несуществующую проблему
если ты ввод осуществляешь у тебя ведь инпут чистится?
Ну так запрещай ввод, если инпут пустой и не нужно этого лишнего кода. На кнопки формы дебаунс не вешают.

2021-05-31 12:09 UTC, zenby commented on src/js/weather.js
> +  }
то, что ты изменил тут, не будет работать или будет работать с ошибками. Ты должен в catch блоке понять какой код ошибки в боди (который передает бекенд) и если он соответствует не понятому беком кодом (ты должен проверить это заранее введя странный город в инпут) показать нужное сообщение. Если условия не выполняются, то окей, можешь показать `err.message`

2021-05-31 12:11 UTC, zenby commented on src/js/weather.js
> +  });
это только прикольно, но не более того. Проблема в том, что оно не соответсвует тому, что ты вводил, если перенесешься по карте на другой город - погода не изменится. Поэтому если это останется будет видно, что этот момент ты не доделал.

2021-06-12 17:45 UTC, zenby commented on src/js/getTime.js
> +  }
- такие функции хорошо оформлять через тернарный оператор
- название функции плохое

2021-06-12 17:45 UTC, zenby commented on src/js/getTime.js
> +  time.innerHTML = `${hour.padStart(2, "0")}:${min.padStart(2, "0")}:${sec.padStart(2, "0")}`;
[hour, min, sec].map(value => value.toString().padStart(2, "0")).join(':')
и тогда выше не нужно повторять toString() трижды. 

Но это так усовершенствование, которое можно и не делать - у тебя нагляднее написано.

2021-06-12 17:45 UTC, zenby commented on src/js/getLocation.js
> +export const libary = {
что значит это слово?

2021-06-12 17:45 UTC, zenby commented on src/js/getLocation.js
> +    clear: [1000],
в этом блоке все поля должны иметь одну и ту же структуру в именовании. где связь например между 
clear, partyCloudy, codesOfLIghtRain ?

2021-06-12 17:45 UTC, zenby commented on src/js/weather.js
> +}
Чуть чуть недорефакторил
```
function createFutureWeatherInfo(data) {
  weatherOn3Days.innerHtml = ''
  data.forecast.forecastday.forEach((el) => {
    const celsOrFahrenheit = Math.round(el.day[maxTempInCelsOrFahrenheit]);
    const iconCode = libary.icons.getIcon(el.day.condition.code);
    const weekDay =  new Date(el.date).toLocaleString(language, {weekday: "long"})
    weatherOn3Days.innerHTML += `
   <div class="blockDayWeather">
    <div class="weekDayNext>
      <div class="week_day">${weekDay}</div>
    </div>
    <div class='weekDayWeather'>
      <div class="next_day_weather">${celsOrFahrenheit}&#176</div>
       <img src='${iconCode}'/>
    </div>
   <div>`;
  });
}
```

2021-06-12 17:45 UTC, zenby commented on src/js/weather.js
> +    document.body.style.backgroundAttachment = "fixed";
151 - 152 строка не меняются, значит их можно отнести в css 
149 150 зачем ты дважды устанавливаешь картинку, разве одного раза недостаточно?

2021-06-12 17:45 UTC, zenby commented on src/js/weather.js
> +    if (inputCity !== city) {
у тебя хоть иногда бывают одинаковые города, если твой инпут чистится? Зачем этот if здесь? 
Также у тебя когда меняется язык или температура перезагружается картинка - мне кажется хорошо было бы делать это только при смене города. Также бекраунд во время загрузки выглядит очень плохо (я о  сером фоне)

2021-06-12 17:45 UTC, zenby commented on src/styles/_base.scss
> +}
это миксин по сути своей, значит заноси его в файл mixins

2021-06-12 17:45 UTC, zenby commented on src/styles/_components.scss
> +.weahter_info_title {
опечатка

2021-06-12 17:45 UTC, zenby commented on src/styles/_components.scss
> +.currentWeather {
можешь не исправлять, но css именования классов выглядят по меньшей мере странно
Если взять этот пример, то у тебя есть варианты в виде
- currentWeather
- current_weather

Еще в принципе используют такой вариант.  
- current-weather

У тебя в проекте должно быть все в одном стиле.
Также ты плохо используешь вложенность в sсss. У тебя очень много можно разбить на более крупные блоки, тогда понятнее файл будет читаться. Сейчас ты не используешь достаточно преимущества scss, которые бы демонстрировали, что ты его знаешь на неплохом уровне.

2021-06-12 17:45 UTC, zenby commented on src/styles/style.scss
> +}
удалить

2021-06-12 17:45 UTC, zenby commented on src/styles/style.scss
> +  }
2 блока выше можно в один сгруппировать

2021-06-12 17:45 UTC, zenby commented on src/styles/_components.scss
> +}
лучше в проекте взять за правило не использовать селекторы в виде хтмл тегов, потому что потом словишь проблемы, когда будешь его расширять. Сейчас с одним инпутом пока все хорошо. Но я бы лучше обозвал как-нибудь форму `form id="city-input-form"` и потом в стилях использовал бы так
```
#city-input-form {
 // стили формы 
  & > input {
 // стили инпута
 & > button {
// стили кнопки

```

Тогда у тебя получается большой блок формы и кнопки и инпуты снаружи точно не перестилятся. Да и читать удобно, что ты понимаешь что это форма, и внутрь лезть тебе не нужно, например, когда читаешь этот файл.

2021-06-12 17:45 UTC, zenby commented on src/styles/_constants.scss
> +$mobile: 400px;
эти 3 переменные используются ради переменных, они только по одному разу используются.

2021-06-13 13:44 UTC, zenby requested changes
Вот еще по-мелочи нашел замечаний.

Также, после твоих исправлений помечай мои комменты как resolved, чтобы они у меня не висели. В таком случае они мне мешают и не всегда понятно, исправил ты что-либо или нет.

2021-06-13 13:44 UTC, zenby commented on src/js/getLocation.js
> +    text: "",
Почему это поле пустое в обоих языках?

2021-06-13 13:44 UTC, zenby commented on src/js/getLocation.js
> +    sunny: "./assets/day.svg",
Что это за поле? Если оно надо, почему его нет в русском?

2021-06-13 13:44 UTC, zenby commented on src/js/getLocation.js
> +    codesClear: [1000],
Замени эти поля в объекте icon на переменную `iconCodes` внутри функции getIcon
они тебе нужны только внутри этой функции, нет смысла добавлять их в объект. В качестве ключей используй ссылки на иконки

2021-06-13 13:44 UTC, zenby commented on src/js/getLocation.js
> +      if (libary.icons.codesOfLightRain.includes(code)) {
Для того чтобы убрать эту кучу if в функции я бы предложил использовать 
[Object.entries()](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/entries) на объекте `iconCodes`, тогда ты сможешь по типу иконки сразу получать ее url

2021-06-13 13:44 UTC, zenby commented on src/js/getLocation.js
> +      if (libary.icons.codesClear.includes(code)) {
Для этих манипуляций ты можешь завести переменную `iconByTimeOfDay` и если иконка содержится в этом массиве - добавь к ее пути `day` или `night`. Только надо сначала переименовать пути этих иконок соответственно

2021-06-13 13:44 UTC, zenby commented on src/js/getLocation.js
> +};
А почему этот файл называется getLocation?

2021-06-13 13:44 UTC, zenby commented on src/js/getTime.js
> +export function getTimesOfDay(hour = new Date().getHours()) {
Это плохо, что ты экспортируешь эту функцию из фала `getTime` и используешь ее в файле `getLocation`, в то же время ты тут используешь объект `library `из файла `getLocation`.
в реальных проектах так сделать не стоит. В этой ситуации тебе надо вынести функцию  `getTimesOfDay` в другой файл и импортировать ее в `getTime.js` и `getLocation.js`

2021-06-13 13:44 UTC, zenby commented on src/js/getTime.js
> +import loc, { libary } from "./getLocation.js";
что такое loc? я не вижу его использования в этом файле

2021-06-13 13:44 UTC, zenby commented on src/js/weather.js
> +});
Мне не нравится, что у тебя в проекте нет файла, с которого хочется начать читать твой код. ничего похожего на app.js index.js или initialize.js
Откуда начинает выполняться твой код?

2021-06-13 13:44 UTC, zenby commented on src/js/getTime.js
> +  const weekDay = today.getDate();
Переменная называется день недели. Разве она содержит значения дня недели?

2021-06-13 13:44 UTC, zenby commented on src/js/getTime.js
> +  const today = new Date(new Date().toLocaleString("en-US", { timeZone: `${timezone}` }));
зачем оборачивать timezone в строку? 
Прочитай как с[оздавать свойства из переменной](https://learn.javascript.ru/object#svoystvo-iz-peremennoy) и исправь у себя!

2021-06-13 13:44 UTC, zenby commented on src/js/getTime.js
> +  time.innerHTML = `${hour.padStart(2, "0")}:${min.padStart(2, "0")}:${sec.padStart(2, "0")}`;
Почему не использовать встроенные функции языка такие как `toLocalTimeString` ?

2021-06-13 13:44 UTC, zenby commented on src/js/getTime.js
> +  getTimesOfDay(hour);
А зачем тут вызывается эта функция? Что она делает?

2021-06-13 13:44 UTC, zenby commented on src/js/getTime.js
> +  localStorage.setItem("language", e.target.value);
Ты ведь уже получил значение переменной `e.target.value` на 36й строке, можно просто написать `language`

2021-06-13 13:44 UTC, zenby commented on src/js/getTime.js
> +export let language = localStorage.getItem("language") || "EN";
Почему эта переменная экспортируется из файла `getTime`? это не логично.
Тем более ниже в этом файле ты меняешь значение этой переменной и это очень сложно читать. Я бы предложил тебе вынести получение и установку языка в тот файл, где находятся переводы и экспортировать оттуда функции `getLanguage `и `setLanguage`, которые читают и записывают значение языка в `localStorage`.

2021-06-13 13:44 UTC, zenby commented on src/js/getTime.js
> +  changeLanguage(event);
Почему функция `changeLanguage `в принципе должна что-то знать об ивентах? передавай в нее сразу язык

2021-06-13 13:44 UTC, zenby commented on src/js/getTime.js
> +  getWeather(currentLocation.textContent);
Почему функция, которая меняет язык, запрашивает прогноз погоды? Верни getWeather в добавление eventListener-a на кнопку lang

2021-06-13 13:44 UTC, zenby commented on src/js/weather.js
> +  <div>${libary[language].latitude}: ${latitude[0]}&#176 ${latitude[1]}'</div>
Ты проделываешь одинаковые действия для того чтобы отобразить широту и долготу. Ты можешь написать простую функцию которая примет строку с запятой и сразу превратит ее в нужную тебе строку, тебе не придется создавать промежуточные переменные
```
const getCoordinateString = (str) => `${str.replace('.', '&#176')}'`
```

2021-06-13 13:44 UTC, zenby commented on src/js/weather.js
> +function getActualTemp() {
я не понимаю смысл этой функции, она называется getActualTeml но она не возвращает тебе никакую температуру. все эти действия можно разнести по разным частям твоего кода, где они будут читаться гораздо логичнее

2021-06-13 13:44 UTC, zenby commented on src/js/weather.js
> +  currentTempInCelsOrFahrenheit = userChoiceTemperatureUnit === "c" ? "temp_c" : "temp_f";
Зачем тебе эти переменные? ты можешь просто вычитать значение `userChoiceTemperatureUnit` из `localStorage` и дописать это к `temp_ `, `feelslike_`, `maxtemp_` в том месте, где тебе нужно вычитать прогноз погоды

2021-06-13 13:44 UTC, zenby commented on src/js/weather.js
> +      alert("Город не найден. Попробуйте заново");
Где перевод этой строки?

2021-06-13 13:44 UTC, zenby commented on src/js/weather.js
> +  var map = new mapboxgl.Map({
На каждый запрос ты создаешь новую карту, это неправильно. Карта должна быть создана один раз во время инициализации приложения и дальше тебе надо работать с одним и тем же объектом. 
[Вот тут ты можешь посмотреть свойства и методы объекта map](https://docs.mapbox.com/mapbox-gl-js/api/map/#map-instance-members), который ты тут создал и найти там как двигать карту

2021-06-13 13:44 UTC, zenby commented on src/js/weather.js
> +    alert("Что-то пошло не так");
Нет перевода

2021-06-13 13:44 UTC, zenby commented on src/js/weather.js
> +  <div class='info_element'>${libary[language].feel}: ${feelsLikeInfo} &#176</div>
`libary[language].feel`
Этот код должен быть в том месте, где ты меняешь язык. Тут ты просто должен устанавливать новое значение

2021-06-13 13:44 UTC, zenby commented on src/js/weather.js
> +    alert("Ошибка загрузки фонового изображения");
перевод

2021-06-13 13:44 UTC, zenby commented on src/index.html
> +               <option data-value="eng" selected>EN</option>
Это же контрол. Зачем тебе тут data-value если можно использовать просто value
И почему в коде везде ты используешь EN а тут eng? Если eng нужен для API погоды, то ты можешь у себя в коде везде использовать ENG

2021-06-24 07:37 UTC, zenby reviewed
вроде работает

2021-06-24 07:37 UTC, zenby commented on src/js/app.js
> +  });
я писал уже что этот блок делается через select и сетается в value нужное значение. Не нужно помечать все options как unselected и потом ставить то, что выбрали.

2021-06-24 07:37 UTC, zenby commented on src/js/languageUtil.js
> +export function changeLanguage(languag) {
опечатка

2021-06-24 07:37 UTC, zenby commented on src/js/weather.js
> +let maxTempInCelsOrFahrenheit;
избавься от этих 3 переменных. В нужных местах, где берешь данные из полей подставляй userChoiceTemperatureUnit

2021-06-24 07:37 UTC, zenby commented on webpack.config.js
> +      },
блок с xml-loader  тебе не нужен в проекте. Убери его.

2021-06-24 07:37 UTC, zenby commented on package.json
> +    "webpack-cli": "^4.7.0"
установи еще stylelint-scss я вчера его по ошибке удалил, думал он не нужен

2021-06-24 07:37 UTC, zenby commented on src/index.html
> +            <input type="text" name="" id="" placeholder="Search city" required>
зачем здесь пустой name + id?

2021-06-25 14:54 UTC, zenby approved these changes

2021-06-28 19:30 UTC, merged